name = "test"
type = "javascript"
account_id = "296e45790b45c04d3af787d2e8de869c"
workers_dev = true
route = ""
zone_id = ""
kv-namespaces = [
  { binding = "kv", id = "ad5ce80869f746ffbbfefea0a5cfaba5" }
]
