name: worker
on: push
jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Wrangler
      env:
        CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}
      run: |
        npx @cloudflare/wrangler publish
