name: worker
on:
  push:
    branches:
    # Limit to the `master` branch
    - master
jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Wrangler
      env:
        CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        nvm install 13
        nvm use 13
        npm install --global wrangler
        wrangler config
        wrangler publish
